# Generated by Django 4.2.7 on 2023-11-24 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cli_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cli_nombre', models.TextField(blank=True, null=True)),
                ('cli_direccion', models.TextField(blank=True, null=True)),
                ('cli_telefono', models.BigIntegerField(blank=True, null=True)),
                ('cli_correo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('mar_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mar_nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marcas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('prov_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prov_nombre', models.TextField(blank=True, null=True)),
                ('prov_contacto', models.TextField(blank=True, null=True)),
                ('prov_telefono', models.BigIntegerField(blank=True, null=True)),
                ('pro_correo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol_nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usu_nombre', models.TextField(blank=True, null=True)),
                ('usu_apellido_p', models.TextField(blank=True, null=True)),
                ('usu_apellido_m', models.TextField(blank=True, null=True)),
                ('usu_rut', models.TextField(blank=True, null=True)),
                ('usu_password', models.TextField(blank=True, null=True)),
                ('usu_rol', models.ForeignKey(blank=True, db_column='usu_rol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.roles')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('pro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.TextField(blank=True, null=True)),
                ('pro_stock', models.BigIntegerField(blank=True, null=True)),
                ('pro_registro', models.DateTimeField(blank=True, null=True)),
                ('pro_fecha_fencimiento', models.DateField(blank=True, null=True)),
                ('pro_precio', models.BigIntegerField(blank=True, null=True)),
                ('pro_descripcion', models.TextField(blank=True, null=True)),
                ('pro_marca', models.ForeignKey(blank=True, db_column='pro_marca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.marcas')),
                ('pro_proveedore', models.ForeignKey(blank=True, db_column='pro_proveedore', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.proveedores')),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('his_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('his_fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('his_modificacion', models.TextField(blank=True, null=True)),
                ('his_cantidad', models.BigIntegerField(blank=True, null=True)),
                ('his_observacion', models.TextField(blank=True, null=True)),
                ('his_cliente', models.ForeignKey(blank=True, db_column='his_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.clientes')),
                ('his_producto', models.ForeignKey(blank=True, db_column='his_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.productos')),
                ('his_usuario', models.ForeignKey(blank=True, db_column='his_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.usuarios')),
            ],
            options={
                'db_table': 'historial',
                'managed': True,
            },
        ),
    ]
